version: '2'
services:
  mysql:
    image: "mysql:5.7"
    volumes:
      - "/usr/local/mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=
    container_name: "mysql"
    ports:
      - 3306:3306
    restart: always
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - MYSQL_ROOT_PASSWORD=
    container_name: "phpmyadmin"
    ports:
      - 8080:80
    restart: always
    links:
      - mysql:db
  bnetd:
    image: "quay.io/danfercf/server-pvpgn-x64:latest"
    volumes:
      - "/usr/local/pvpgn/etc:/usr/local/pvpgn/etc"
      - "/usr/local/pvpgn/log:/var/log/pvpgn"
      - "/usr/local/ghost/maps:/usr/local/pvpgn/maps"
    container_name: bnetd
    ports:
      - 6112:6112
      - 6200:6200
    restart: always
    links:
      - mysql:db
networks:
  default:
    external:
      name: pvpgn_default
